/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.vista;

import co.com.modelo.Datos;
import ecuacionesdiferenciales.EcuacionesDiferenciales;
import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;


/**
 *
 * @author FABIO
 */
public class JDialogOperaciones extends javax.swing.JDialog {

    /**
     * Creates new form JDialogOperaciones
     */
    JFreeChart grafica;
    DefaultCategoryDataset datosGrafica = new DefaultCategoryDataset();
   Datos datos = new Datos();
   static ChartPanel Panel;
   JFrame Ventana;
    public JDialogOperaciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextPoblacionInicial = new javax.swing.JTextField();
        TextTiempo = new javax.swing.JTextField();
        TextPoblacionFina = new javax.swing.JTextField();
        ButtonCalcular = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textAumentoPoblacion = new javax.swing.JTextField();
        textCantidadAnios = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        labelRespuesta1 = new javax.swing.JLabel();
        labelRespuesta2 = new javax.swing.JLabel();
        labelRespuesta3 = new javax.swing.JLabel();
        labelRespuesta4 = new javax.swing.JLabel();
        labelRespuesta5 = new javax.swing.JLabel();
        labelRespuesta6 = new javax.swing.JLabel();
        buttonGraficar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("DATOS CONOCIDOS");

        jLabel2.setText("Poblacion Inicial");

        jLabel3.setText("Tiempo");

        jLabel4.setText("Poblacion Final");

        TextPoblacionInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPoblacionInicialActionPerformed(evt);
            }
        });

        TextPoblacionFina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPoblacionFinaActionPerformed(evt);
            }
        });

        ButtonCalcular.setText("Calcular");
        ButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalcularActionPerformed(evt);
            }
        });

        jLabel5.setText("Aumento en la poblacion");

        jLabel6.setText("Cantidad años");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRespuesta2)
                    .addComponent(labelRespuesta3)
                    .addComponent(labelRespuesta4)
                    .addComponent(labelRespuesta5)
                    .addComponent(labelRespuesta6)
                    .addComponent(labelRespuesta1))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRespuesta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRespuesta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRespuesta3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRespuesta4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRespuesta5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRespuesta6)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        buttonGraficar.setText("Graficar");
        buttonGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGraficarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextPoblacionInicial)
                                    .addComponent(TextTiempo)
                                    .addComponent(TextPoblacionFina)
                                    .addComponent(textAumentoPoblacion)
                                    .addComponent(textCantidadAnios, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonCalcular)
                                .addGap(33, 33, 33)
                                .addComponent(buttonGraficar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TextPoblacionInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TextTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextPoblacionFina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textAumentoPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textCantidadAnios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonCalcular)
                    .addComponent(buttonGraficar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextPoblacionInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPoblacionInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPoblacionInicialActionPerformed

    private void TextPoblacionFinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPoblacionFinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPoblacionFinaActionPerformed

    private void ButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalcularActionPerformed
        // TODO add your handling code here:
        /*
        public static void crecimeintoPoblacional(
            double poblacionInicial,
            int tiempo,
            double poblacionFinal,
            int aumentoPoblacion,
            int cantidadAnios)
         */
        
        datos.setPoblacionInicial(new Double(TextPoblacionInicial.getText()));
        datos.setTiempo(new Integer(TextTiempo.getText()));
        datos.setPoblacionFinal(new Double(TextPoblacionFina.getText()));
        datos.setPoblacionFinal(new Double(TextPoblacionFina.getText()));
        datos.setAumentoPoblacion(new Integer(textAumentoPoblacion.getText()));
        datos.setCantidadAnios(new Integer(textCantidadAnios.getText()));
        if(datos.getPoblacionFinal() ==0){
            textCantidadAnios.setVisible(false);
            jLabel6.setVisible(false);
        }else{
           textCantidadAnios.setVisible(true); 
           jLabel6.setVisible(false);
        }
        String respuesta = EcuacionesDiferenciales.crecimeintoPoblacional(datos.getPoblacionInicial(), datos.getTiempo(), datos.getPoblacionFinal(), datos.getAumentoPoblacion(), datos.getCantidadAnios());
        String[] tokens = respuesta.split("\\|");

        labelRespuesta1.setText(tokens[0]);
        labelRespuesta2.setText(tokens[1]);
        labelRespuesta3.setText(tokens[2]);
        labelRespuesta4.setText(tokens[3]);
        labelRespuesta5.setText(tokens[4]);
        labelRespuesta6.setText(tokens[5]);               
    }//GEN-LAST:event_ButtonCalcularActionPerformed

    private void buttonGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGraficarActionPerformed
        // TODO add your handling code here:
        
        datosGrafica.addValue(datos.getPoblacionInicial(), "Poblacion Inicial", "2019");
        datosGrafica.addValue(datos.getPoblacionFinal(), "Poblacion Final", 2019+(int)EcuacionesDiferenciales.t+"");        
        grafica = ChartFactory.createBarChart3D("Aumento poblacional", "Tiempo en años", "Cantidad Habitantes", datosGrafica, PlotOrientation.VERTICAL, true, true, false);
        if(Panel == null){
            Panel = new ChartPanel(grafica);
            Ventana = new JFrame("JFreeChart");
        }else{
            Panel.setChart(grafica);
        }
        
        //
        
        Ventana.getContentPane().add(Panel);
        Ventana.pack();
        Ventana.setVisible(true);
        //Ventana.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_buttonGraficarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JDialogOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JDialogOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JDialogOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JDialogOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                JDialogOperaciones dialog = new JDialogOperaciones(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCalcular;
    private javax.swing.JTextField TextPoblacionFina;
    private javax.swing.JTextField TextPoblacionInicial;
    private javax.swing.JTextField TextTiempo;
    private javax.swing.JButton buttonGraficar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelRespuesta1;
    private javax.swing.JLabel labelRespuesta2;
    private javax.swing.JLabel labelRespuesta3;
    private javax.swing.JLabel labelRespuesta4;
    private javax.swing.JLabel labelRespuesta5;
    private javax.swing.JLabel labelRespuesta6;
    private javax.swing.JTextField textAumentoPoblacion;
    private javax.swing.JTextField textCantidadAnios;
    // End of variables declaration//GEN-END:variables

    public void init() {
        Datos datos = new Datos();
        TextPoblacionInicial.setText(datos.getPoblacionInicial() + "");
        TextTiempo.setText(datos.getTiempo() + "");
        TextPoblacionFina.setText(datos.getPoblacionFinal() + "");
        textAumentoPoblacion.setText(datos.getAumentoPoblacion() + "");
        textCantidadAnios.setText(datos.getCantidadAnios() + "");
        
      /*
        datosGrafica.addValue(datos.getPoblacionInicial(), "Negocio 1", "Poblacion Inicial");
        datosGrafica.addValue(datos.getPoblacionFinal(), "Negocio 2", "Poblacion Final");        
        grafica = ChartFactory.createBarChart3D("Aumento poblacional", "Tiempo", "Cantidad Habitantes", datosGrafica, PlotOrientation.VERTICAL, true, true, false);
        
        //series= new XYSeries("Fabio");
        //series.add(datos.getPoblacionInicial(),0);
        //series.add(datos.getPoblacionFinal(),datos.getTiempo());
        //_datos = new XYSeriesCollection(series);
        //grafica = ChartFactory.createXYLineChart("Aumento poblacional", "Cantidad Habitantes", "Tiempo", _datos, PlotOrientation.HORIZONTAL, rootPaneCheckingEnabled, rootPaneCheckingEnabled, rootPaneCheckingEnabled);
        
        ChartPanel Panel = new ChartPanel(grafica);        
        JFrame Ventana = new JFrame("JFreeChart");
        Ventana.getContentPane().add(Panel);
        Ventana.pack();
        Ventana.setVisible(true);
        Ventana.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);*/
    }

}
