/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.vista;

import co.com.modelo.Datos;
import ecuacionesdiferenciales.EcuacionesDiferenciales;
import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author FABIO
 */
public class JFrameOperaciones extends javax.swing.JFrame {

    /**
     * Creates new form JFrameOperaciones
     */
    JFreeChart grafica;
    DefaultCategoryDataset datosGrafica = new DefaultCategoryDataset();

    public JFrameOperaciones() {
        initComponents();
        init();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextPoblacionInicial = new javax.swing.JTextField();
        TextTiempo = new javax.swing.JTextField();
        TextPoblacionFina = new javax.swing.JTextField();
        textAumentoPoblacion = new javax.swing.JTextField();
        textCantidadAnios = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        labelRespuesta1 = new javax.swing.JLabel();
        labelRespuesta2 = new javax.swing.JLabel();
        labelRespuesta3 = new javax.swing.JLabel();
        labelRespuesta4 = new javax.swing.JLabel();
        labelRespuesta5 = new javax.swing.JLabel();
        labelRespuesta6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Poblacion Inicial");

        jLabel2.setText("Tiempo");

        jLabel3.setText("Poblacion Final");

        jLabel4.setText("Aumento en la Poblacion");

        jLabel5.setText("Cantidad Años");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        labelRespuesta1.setText("jLabel6");

        labelRespuesta2.setText("jLabel7");

        labelRespuesta3.setText("jLabel8");

        labelRespuesta4.setText("jLabel9");

        labelRespuesta5.setText("jLabel10");

        labelRespuesta6.setText("jLabel11");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRespuesta6)
                    .addComponent(labelRespuesta5)
                    .addComponent(labelRespuesta4)
                    .addComponent(labelRespuesta3)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelRespuesta2)
                            .addComponent(labelRespuesta1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textCantidadAnios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textAumentoPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextPoblacionFina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextPoblacionInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(46, 46, 46)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(TextPoblacionInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TextTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TextPoblacionFina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textAumentoPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textCantidadAnios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(labelRespuesta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelRespuesta2))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelRespuesta3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelRespuesta4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelRespuesta5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelRespuesta6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Datos datos = new Datos();
        datos.setPoblacionInicial(new Double(TextPoblacionInicial.getText()));
        datos.setTiempo(new Integer(TextTiempo.getText()));
        datos.setPoblacionFinal(new Double(TextPoblacionFina.getText()));
        datos.setPoblacionFinal(new Double(TextPoblacionFina.getText()));
        String respuesta = EcuacionesDiferenciales.crecimeintoPoblacional(datos.getPoblacionInicial(), datos.getTiempo(), datos.getPoblacionFinal(), datos.getAumentoPoblacion(), datos.getCantidadAnios());
        String[] tokens = respuesta.split("\\|");

        labelRespuesta1.setText(tokens[0]);
        labelRespuesta2.setText(tokens[1]);
        labelRespuesta3.setText(tokens[2]);
        labelRespuesta4.setText(tokens[3]);
        labelRespuesta5.setText(tokens[4]);
        labelRespuesta6.setText(tokens[5]);

        datosGrafica.addValue(datos.getPoblacionInicial(), "Poblacion Inicial", "Poblacion Inicial");
        datosGrafica.addValue(datos.getPoblacionFinal(), "Poblacion Final", "Poblacion Final");
        grafica = ChartFactory.createBarChart3D("Aumento poblacional", "Tiempo", "Cantidad Habitantes", datosGrafica, PlotOrientation.VERTICAL, true, true, false);
        grafica.setBorderVisible(rootPaneCheckingEnabled);
        
        ChartPanel Panel = new ChartPanel(grafica);
        //jPanel2 = new javax.swing.JPanel();
        //jPanel2.
        //JFrame Ventana = new JFrame("JFreeChart");
        this.getContentPane().add(Panel);
        this.pack();
        //this.setVisible(true);
        //this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JFrameOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JFrameOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JFrameOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JFrameOperaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new JFrameOperaciones().setVisible(true);
//            }
//        });
//    }

    public void init() {
        Datos datos = new Datos();
        TextPoblacionInicial.setText(datos.getPoblacionInicial() + "");
        TextTiempo.setText(datos.getTiempo() + "");
        TextPoblacionFina.setText(datos.getPoblacionFinal() + "");
        textAumentoPoblacion.setText(datos.getAumentoPoblacion() + "");
        textCantidadAnios.setText(datos.getCantidadAnios() + "");

        /*
        datosGrafica.addValue(datos.getPoblacionInicial(), "Negocio 1", "Poblacion Inicial");
        datosGrafica.addValue(datos.getPoblacionFinal(), "Negocio 2", "Poblacion Final");        
        grafica = ChartFactory.createBarChart3D("Aumento poblacional", "Tiempo", "Cantidad Habitantes", datosGrafica, PlotOrientation.VERTICAL, true, true, false);
        
        //series= new XYSeries("Fabio");
        //series.add(datos.getPoblacionInicial(),0);
        //series.add(datos.getPoblacionFinal(),datos.getTiempo());
        //_datos = new XYSeriesCollection(series);
        //grafica = ChartFactory.createXYLineChart("Aumento poblacional", "Cantidad Habitantes", "Tiempo", _datos, PlotOrientation.HORIZONTAL, rootPaneCheckingEnabled, rootPaneCheckingEnabled, rootPaneCheckingEnabled);
        
        ChartPanel Panel = new ChartPanel(grafica);        
        JFrame Ventana = new JFrame("JFreeChart");
        Ventana.getContentPane().add(Panel);
        Ventana.pack();
        Ventana.setVisible(true);
        Ventana.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);*/
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextPoblacionFina;
    private javax.swing.JTextField TextPoblacionInicial;
    private javax.swing.JTextField TextTiempo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelRespuesta1;
    private javax.swing.JLabel labelRespuesta2;
    private javax.swing.JLabel labelRespuesta3;
    private javax.swing.JLabel labelRespuesta4;
    private javax.swing.JLabel labelRespuesta5;
    private javax.swing.JLabel labelRespuesta6;
    private javax.swing.JTextField textAumentoPoblacion;
    private javax.swing.JTextField textCantidadAnios;
    // End of variables declaration//GEN-END:variables
}
